CANONICAL_CASES = [
    {
        "id": "allow",
        "expected": "ALLOW_COD",
        "order": {
            "order_id": "ord_blr_vet_01",
            "pincode": "560038",
            "address": "Flat 12B, 4th Floor, 18 12th Main, HAL 2nd Stage, Indiranagar",
            "amount": 899,
            "account_age_days": 640,
            "prepaid_orders": 11,
            "prior_rto_count": 0,
            "orders_count": 24,
            "phone": "9876543210",
            "customer_name": "Ananya Rao",
        },
    },
    {
        "id": "force",
        "expected": "FORCE_PREPAID",
        "order": {
            "order_id": "ord_siwan_temple_01",
            "pincode": "841226",
            "address": "near temple",
            "amount": 3499,
            "account_age_days": 2,
            "prepaid_orders": 0,
            "prior_rto_count": 2,
            "orders_count": 0,
            "phone": "9123456780",
            "customer_name": "Ravi Kumar",
        },
    },
    {
        "id": "stop",
        "expected": "STOP",
        "order": {
            "order_id": "ord_bad_pin_01",
            "pincode": "56",
            "address": "12 MG Road, Shivajinagar",
            "amount": 499,
            "account_age_days": 90,
            "prepaid_orders": 1,
            "prior_rto_count": 0,
            "orders_count": 3,
            "phone": "9000000000",
            "customer_name": "Test Drop",
        },
    },
]
